backend:
  name: git-gateway
  branch: main
media_folder: "src/media" # Media files will be stored in the repo under images/uploads
public_folder: "/" # The src attribute for uploaded media
collections:

  - name: settings
    label: Settings
    files:
      - name: site
        label: Site Settings
        file: src/data/site.yml
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Provider, name: provider, widget: string}
          - {label: Email, name: email, widget: string}
          - {label: URL, name: url, widget: string}
          - {label: Preview Image, name: preview_image, widget: image}
          - {label: Favicon, name: favicon, widget: image}
          - label: Social Profiles
            name: social_links
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: URL, name: href, widget: string}
          - label: Footer Links
            name: footer_links
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: URL, name: href, widget: string}
              - {label: Open in new tab, name: target_blank, widget: boolean, required: false}
      - name: contact
        label: Contact Section
        file: src/data/contact.yml
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - label: Person
            name: person
            widget: object
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Title, name: title, widget: string, required: false}
              - {label: Address, name: address, widget: markdown, required: false}
              - {label: Phone, name: phone, widget: string, required: false}
          - {label: Call to Action (Send email), name: send_email, widget: string}
          - {label: Contact us, name: contact_us, widget: string}
          - {label: Connect with us, name: connect_with_us, widget: string}
      - name: header
        label: Header Section
        file: src/data/header.yml
        fields:
          - label: Call-to-Action Buttons
            name: cta
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: URL, name: href, widget: string}
              - {label: Open in new tab, name: target_blank, widget: boolean, required: false}
      - name: about
        label: About the Course
        file: src/data/about.yml
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: text}
          - {label: Body, name: body, widget: text}
          - name: questions
            label: Questions & Answers
            widget: list
            fields:
              - {label: Question, name: q, widget: string}
              - {label: Answer, name: a, widget: text}
              - {label: Image, name: image, widget: image}
          - name: at_a_glance
            label: At a Glance
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - name: properties
                label: Course Properties
                widget: list
                fields:
                  - {label: Title, name: title, widget: string}
                  - {label: Image, name: image, widget: image}
              - {label: Footnote, name: footnote, widget: text}
          - name: overview
            label: Course Overview Section
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: text}
              - name: properties
                label: Course Details
                widget: list
                fields:
                  - {label: Name, name: term, widget: string}
                  - {label: Value, name: deed, widget: text, required: false}
                  - name: list
                    label: List
                    required: false
                    widget: list
                    fields: 
                      - {label: Title, name: title, widget: string}
                      - {label: Intro, name: intro, widget: text, required: false}
                      - label: Items
                        name: items
                        required: false
                        widget: list
                        field: {label: Item, name: item, widget: string}
          - name: modules_section
            label: Modules Section
            widget: object
            fields:
              - {name: course_content, label: Course Content, widget: string}
              - {name: recommended_knowledge, label: Recommended Knowledge, widget: string}
              - {name: no_prior_knowledge, label: No prior knowledge required, widget: string}
              - {name: dates, label: Dates & Registration, widget: string}
              - {name: registerUrl, label: Registration URL, widget: string}
              - {name: no_registration, label: Applications are not open, widget: markdown}
              - {name: course_regime, label: Course Regime, widget: markdown}
          - name: discover_modules
            label: Discover Modules Section
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: text}
      - name: partners
        label: Partners
        file: src/data/partners.yml
        fields:
          - {label: Title, name: title, widget: string}
          - name: items
            label: Partners
            label_singular: Partner
            widget: list
            fields:
              - {name: name, label: Name, widget: string}
              - {name: logo, label: Logo, widget: image}

  - name: modules
    label: Modules
    label_singular: Module
    folder: src/collections/modules
    extension: yml
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Full Title", name: "fullTitle", widget: "string", required: false}
      - {label: "Level", name: "level", widget: "relation", collection: "levels", search_fields: ["title", "order"], value_field: "title"} 
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Description", name: "desc", widget: "markdown"}
      - {label: "Course contents", name: "contents", widget: "markdown"}
      - {label: "Recommended knowledge for participation", name: "recommendedKnowledge", widget: "text", required: false}
      - {label: "Dates and registration", name: "dates", widget: "markdown", required: false}
      - {label: "Registration URL", name: "registerUrl", widget: "string", required: false}
      - {label: "Contact", name: "contacts", widget: "relation", collection: "contacts", search_fields: ["name", "role"], value_field: "name", required: false} 
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Icon", name: "icon", widget: "image", required: false}
      - {label: "Order", name: "order", widget: "number", default: 0}

  - name: levels
    label: Levels
    label_singular: Level
    folder: src/collections/levels
    extension: yml
    slug: "{{order}}-{{title}}"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Summary, name: summary, widget: text}
      - {label: Order, name: order, widget: number, default: 0}

  - name: contacts
    label: Contacts
    label_singular: Contact
    folder: src/collections/contacts
    extension: yml
    create: true
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string", required: false}
      - {label: "Address", name: "address", widget: "text", required: false}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Phone", name: "phone", widget: "string", required: false}
      - {label: "Fax", name: "fax", widget: "string", required: false}
      - {label: "Contact URL", name: "contact", widget: "string", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
