backend:
  name: git-gateway
  branch: main
media_folder: "src/media" # Media files will be stored in the repo under images/uploads
public_folder: "/" # The src attribute for uploaded media
collections:
  - name: modules
    label: Modules
    label_singular: Module
    folder: src/collections/modules
    extension: yml
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Full Title", name: "fullTitle", widget: "string", required: false}
      - {label: "Level", name: "level", widget: "relation", collection: "levels", search_fields: ["title", "order"], value_field: "title"} 
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Description", name: "desc", widget: "markdown"}
      - {label: "Course contents", name: "contents", widget: "markdown"}
      - {label: "Recommended knowledge for participation", name: "recommendedKnowledge", widget: "text", required: false}
      - {label: "Dates and registration", name: "dates", widget: "markdown", required: false}
      - {label: "Registration URL", name: "registerUrl", widget: "string", required: false}
      - {label: "Contact", name: "contact", widget: "relation", collection: "contacts", search_fields: ["name", "role"], value_field: "name", required: false} 
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Icon", name: "icon", widget: "image", required: false}
      - {label: "Order", name: "order", widget: "number", default: 0}

  - name: levels
    label: Levels
    label_singular: Level
    folder: src/collections/levels
    extension: yml
    slug: "{{order}}-{{title}}"
    create: true
    fields:
      - {label: Title, name: title, widget: string}
      - {label: Summary, name: summary, widget: text}
      - {label: Order, name: order, widget: number, default: 0}
      - name: courses
        label: Courses
        label_singular: Course
        required: false
        widget: list
        field: {label: Course, name: course, widget: relation, collection: modules, search_fields: [title], value_field: title}

  - name: contacts
    label: Contacts
    label_singular: Contact
    folder: src/collections/contacts
    extension: yml
    create: true
    identifier_field: name
    fields:
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Role", name: "role", widget: "string", required: false}
      - {label: "Address", name: "address", widget: "text", required: false}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Phone", name: "phone", widget: "string", required: false}
      - {label: "Fax", name: "fax", widget: "string", required: false}
      - {label: "Contact URL", name: "contact", widget: "string", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
